### PR TITLE
New SDK referenced on Template

### PR DESCRIPTION
**Pull request by kse3hi**
# Description
Correct reference on SDK

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [x] Devcontainer can be opened successfully
* [x] Devcontainer can be opened successfully behind a corporate proxy
* [x] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

### CODE REVIEW

**Review by BjoernAtBosch — COMMENTED** [review]
Why not taking latest main (currently: 4cd4ba3add0bf8109183bf5da8cda164622710a5)?

**Comment by kse3hi** [comment]
> Why not taking latest main (currently: 4cd4ba3add0bf8109183bf5da8cda164622710a5)?

I would like first to fix version 0.2 and then release 0.3 version

**Comment by kse3hi** [comment]
> Why not taking latest main (currently: 4cd4ba3add0bf8109183bf5da8cda164622710a5)?

Just forgot to pull the latest changes :) Done.

**Review by BjoernAtBosch — APPROVED** [review]
LGTM

**Pull request merged**
